name: deploy

on:
  push:
    branches: [ main ]

jobs:
  copy_project_on_server:
    name: Copy project on server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create archive with project
        run: |
          mkdir ../GetIPNetworksProd
          cp -TR . ../GetIPNetworksProd
          tar -cvf getipnetworks.tar ../GetIPNetworksProd/

      - name: Copy archive to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          source: "getipnetworks.tar"
          target: "/home/projects/"

  run_scrapyd_in_docker:
    name: Run scrapyd service
    runs-on: ubuntu-latest
    needs: copy_project_on_server
    if: github.ref_name == 'main'
    steps:
      - name: Run docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd /home/projects/
            docker compose -f GetIPNetworksProd/scrapy_infra/docker-compose.yaml down
            docker image rm scrapyd_image
            tar -xf getipnetworks.tar && rm getipnetworks.tar
            rm -f GetIPNetworksProd/.env && touch GetIPNetworksProd/.env
            echo DATABASE_URL="${{ secrets.DATABASE_URL }}" >> GetIPNetworksProd/.env
            echo "${{ secrets.INIT_USER_DB_SQL }}" >> GetIPNetworksProd/scrapy_infra/docker-entrypoint-initdb.d/init-user-db.sql
            docker network ls | grep -w my_network || docker network create my_network
            docker compose -f GetIPNetworksProd/scrapy_infra/docker-compose.yaml up -d --build

  send_message:
    runs-on: ubuntu-latest
    needs: run_scrapyd_in_docker
    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} GetIPNetworks успешно выполнен!
